

export const objects = [
  {id: 1, toggled: false },
  {id: 2, toggled: false },
  {id: 3, toggled: false },
  {id: 4, toggled: false },
  {id: 5, toggled: false },
  {id: 6, toggled: false },
  {id: 7, toggled: false },
  {id: 8, toggled: false },
  {id: 9, toggled: false },
  {id: 10, toggled: false },
  {id: 11, toggled: false },
  {id: 12, toggled: false },
  {id: 13, toggled: false },
  {id: 14, toggled: false },
  {id: 15, toggled: false },
  {id: 16, toggled: false },
  {id: 17, toggled: false },
  {id: 18, toggled: false },
  {id: 19, toggled: false },
  {id: 20, toggled: false },
  {id: 21, toggled: false },
  {id: 22, toggled: false },
  {id: 23, toggled: false },
  {id: 24, toggled: false },
  {id: 25, toggled: false },
]